global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'cozero'
  metrics_path: '/v1/metrics'
  static_configs:
  - targets: [ 'api.cozero.io' ]
  scheme: https

- job_name: 'edelivery'
  metrics_path: '/v1/metrics'
  static_configs:
  - targets: [ 'api.edelivery.cozero.io' ]
  scheme: https
